[package]
name = "valet"
version = "0.1.0"
edition = "2024"

[features]
gui = ["dep:egui"]

[dependencies]
aes-siv = "0.7"
argon2 = "0.5"
egui = { version = "0.32", optional = true }
rand = "0.6"
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio"] }
tokio = { version = "1.46", features = ["full"] }
