/* Generated by cbindgen. Do not edit by hand. */

#ifndef VALET_IPC_H
#define VALET_IPC_H

#pragma once

/* WARNING: this file is autogenerated. */

#include <stddef.h>
#include <stdint.h>

/**
 * Maximum allowed frame payload, 16 MiB. The daemon never returns anywhere
 * near this much data; the cap exists to bound client-side allocations if
 * a peer misbehaves.
 */
#define MAX_FRAME_LEN ((16 * 1024) * 1024)

#define VALET_IPC_OK 0

#define VALET_IPC_ERR_NULL_ARG 1

#define VALET_IPC_ERR_INVALID_UTF8 2

#define VALET_IPC_ERR_IO 3

#define VALET_IPC_ERR_PROTOCOL 4

#define VALET_IPC_ERR_PASSWORD_TOO_LONG 5

/**
 * Opaque client handle. Rust-side representation is [`Handle`]; Swift only
 * ever sees `*mut CValetClient`.
 */
typedef struct ValetClient ValetClient;

typedef struct ValetStr {
  char *ptr;
  uintptr_t len;
} ValetStr;

typedef struct ValetRecordView {
  struct ValetStr uuid;
  struct ValetStr label;
  struct ValetStr username;
  struct ValetStr password;
  struct ValetStr url;
} ValetRecordView;

typedef struct ValetRecordList {
  struct ValetRecordView *items;
  uintptr_t count;
} ValetRecordList;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

#if defined(VALET_IPC_STUB)
int32_t valet_ipc_client_new_stub(struct ValetClient **out);
#endif

int32_t valet_ipc_client_connect(const char *socket_path, struct ValetClient **out);

int32_t valet_ipc_client_unlock(struct ValetClient *client,
                                const char *username,
                                const char *password,
                                uintptr_t password_len);

int32_t valet_ipc_client_list(struct ValetClient *client,
                              const char *const *service_ids,
                              const uintptr_t *service_id_lens,
                              uintptr_t service_ids_count,
                              struct ValetRecordList *out);

void valet_ipc_client_free(struct ValetClient *client);

void valet_ipc_record_list_free(struct ValetRecordList list);

/**
 * Returns the thread-local last error message set by the most recent failing
 * FFI call, or `NULL` if none. The pointer is owned by the thread-local and
 * remains valid until the next FFI call on the same thread.
 */
const char *valet_ipc_last_error(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* VALET_IPC_H */
